# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: oldrel
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
notifications:
  email:
    - fmhoeger@mirsem.org
addons:
  apt:
    packages:
      - libgit2-dev

before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_github("rstudio/rmarkdown"); install.packages("shinytest"); shinytest::installDependencies()'

script:
  - R CMD build .
  - travis_wait 45 R CMD check psyquest_*.tar.gz --as-cran

# after_success:
#   - travis_wait 45 Rscript -e 'covr::codecov()'

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
